name: mercos_challenge
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^1.1.1
  firebase_auth_web: ^1.0.7
  firebase_core: ^1.0.4
  firebase_core_web: ^1.0.2
  google_sign_in: ^4.5.9
  fluttertoast: ^7.1.6
  provider: ^4.0.5
  http: ^0.13.1
  flutter_masked_text: ^0.8.0
  stream_transform: ^0.0.19

  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.5


flutter:

  uses-material-design: true

  assets:
    - assets/images/placeholder.png
